### ISSUE TITLE
Any info on why olympos.min.js won't load?

### ISSUE THREAD

**Issue by nolaandy** [ivandoric/olympos#1]
Gulp is reading the changes of olympos.min.js but when I visit the site and insepct the resources I only see these files in js:
jquery, jquery-migrate, livereload, and wp-emoji-release.

The sass is compiling properly. This is the top of my functions.php 
  `
<?php

/*  Register Scripts and Style */

function theme_register_scripts() {
    wp_enqueue_style( 'olympos-css', get_stylesheet_uri() );
    wp_enqueue_script( 'olympos-js', esc_url( trailingslashit( get_template_directory_uri() ) . 'js/olympos.min.js' ), array( 'jquery' ), '1.0', true );
}
add_action( 'wp_enqueue_scripts', 'theme_register_scripts', 1 );
`

**Comment by ivandoric** [comment]
Hmm that is weird. olympos.min.js doesn't appear in resources for me as well. But it is there. If you view the source you will see it. It is linking to the file, I just don't understand why Chrome doesn't pick it in the resources.

I will check that out. Thanks.

**Comment by nolaandy** [comment]
Unfortunately it isn't visible for me when I view source. I can confirm it's not writing to the site with this basic jquery function:

$("body").click(function() {
    $(this).toggleClass('clicked');
});

It works when I put it in my custom .js file I am calling in header.php
It doesn't work though when I add the same code in main.js, even though in grunt I see this:

[11:12:51] Starting 'uglify'...
[11:12:51] Finished 'uglify' after 787 µs
[11:12:52] c:\wamp\www\wp_dev_andy\content\themes\olympos\js\olympos.min.js relo
aded.

Thanks for the reply.

**Comment by fpaeslima** [comment]
Hey guys, try to use the wp_enqueue_script like this in your function.php


     wp_enqueue_script('olympos-js', get_template_directory_uri() . '/js/olympos.min.js', array(), '1.0.0', 'true');


I hope this works

**Comment by Viktoru** [comment]
Error: Cannot find module 'gulp-livereload'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by ivandoric** [comment]
@Viktoru try doing `npm install --save-dev gulp-livereload` But I suggest you not use livereload at all. Maybe better to use Browsersync. I will have to update this repo soon.
