### ISSUE TITLE
NPM error when running npm install on initial use

### ISSUE THREAD

**Issue by prestontoor** [ivandoric/olympos#5]
Hi there,

Thank you for this theme, I look forward to using it! I love that it has NPM and SASS and plan to use this with CSS Grid and Flexbox and NO BOOTSTRAP! Yay.

Anyhow, I am having an issue with NPM when I initially run npm install. I'm keeping the package.json and gulp.js file in the theme folder, but still when I run npm install it gives me this error (please any help would be appreciated):

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/prestontoor/Desktop/development/test/wp-content/themes/olympos/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/prestontoor/Desktop/development/test/wp-content/themes/olympos/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/prestontoor/Desktop/development/test/wp-content/themes/olympos/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by prestontoor** [comment]
Figured it out on this GitHub remark: https://github.com/schnerd/d3-scale-cluster/issues/7


His answer:
this library contains a native addon for extra performance in node environments, what this means is that you should have a c compiler installed on your system. This is fairly common in the node ecosystem.

See instructions here: https://github.com/nodejs/node-gyp#on-macos

In most cases this is as easy as running xcode-select --install on your mac.
